# Organization (5 points)
#### Outputted results from runnning the notebook cells
#### Each cell is clean and directly follows after a question
#### SQL syntax and naming convention is being followed as discussed in class
#### In every cell, the appropriate package imports are being utilized

# Setup (20 points)

#### Output the path of the conda enviroment for this notebook - (5 points)

In [4]:
import sys
print(sys.executable)

/opt/anaconda3/envs/sql_class/bin/python

#### Show the package version for sklearn, pandas, numpy, plotly, and sqlite - (5 points)

In [33]:
import pandas
import sklearn
import numpy
import sqlite3
import plotly
print(pandas.__version__)
print(sklearn.__version__)
print(numpy.__version__)
print(sqlite3.sqlite_version)
print(plotly.__version__)

2.3.3
1.7.2
2.2.5
3.51.1
6.5.0

#### Output cloning of the repo - (5 points)

In [8]:
!git rev-parse --show-toplevel

/Users/hartaig/Documents/Projects/columbia-sql-course

#### Show the filepath of the current notebook - (5 points)

In [10]:
import os
os.getcwd()

'/Users/hartaig/Documents/Projects/columbia-sql-course/submissions/test'

# Connect to the Lahman Database in SQLite (10 points)

In [ ]:
import sqlite3 # 5 points for importing sqlite3

# 5 points for connecting to the database
# add file path to lahman_1871-2022.sqlite
#conn = sqlite3.connect("<file path to lahman_1871-2022.sqlite>")
conn = sqlite3.connect("/Users/hartaig/Documents/Projects/Columbia SQL/Spring 2026/lahman_1871-2022.sqlite")
cursor = conn.cursor()

# Show the table names from the Lahman database (5 points)

In [12]:
# 5 points for executing the query and showing the output
cursor.execute("""
SELECT name
FROM sqlite_master
WHERE type='table';
""")

print(cursor.fetchall())

[('AllstarFull',), ('Appearances',), ('AwardsManagers',), ('AwardsPlayers',), ('AwardsShareManagers',), ('AwardsSharePlayers',), ('Batting',), ('BattingPost',), ('CollegePlaying',), ('Fielding',), ('FieldingOF',), ('FieldingOFsplit',), ('FieldingPost',), ('HallOfFame',), ('HomeGames',), ('Managers',), ('ManagersHalf',), ('Parks',), ('People',), ('Pitching',), ('PitchingPost',), ('Salaries',), ('Schools',), ('SeriesPost',), ('Teams',), ('TeamsFranchises',), ('TeamsHalf',)]

# Explore team statistics (5 points)
#### Q1. Show the rows of the Team table (1 point)

In [19]:
import pandas as pd
query = """
SELECT *
FROM Teams
"""
df = pd.read_sql(query, conn)
df

,yearID,lgID,teamID,franchID,divID,Rank,G,Ghome,W,L,...,DP,FP,name,park,attendance,BPF,PPF,teamIDBR,teamIDlahman45,teamIDretro
0,1871,NA,BS1,BNA,None,3,31,NaN,20,10,...,24,0.834,Boston Red Stockings,South End Grounds I,NaN,103,98,BOS,BS1,BS1
1,1871,NA,CH1,CNA,None,2,28,NaN,19,9,...,16,0.829,Chicago White Stockings,Union Base-Ball Grounds,NaN,104,102,CHI,CH1,CH1
2,1871,NA,CL1,CFC,None,8,29,NaN,10,19,...,15,0.818,Cleveland Forest Citys,National Association Grounds,NaN,96,100,CLE,CL1,CL1
3,1871,NA,FW1,KEK,None,7,19,NaN,7,12,...,8,0.803,Fort Wayne Kekiongas,Hamilton Field,NaN,101,107,KEK,FW1,FW1
4,1871,NA,NY2,NNA,None,5,33,NaN,16,17,...,14,0.840,New York Mutuals,Union Grounds (Brooklyn),NaN,90,88,NYU,NY2,NY2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3010,2022,NL,PIT,PIT,C,5,162,81.0,62,100,...,152,0.979,Pittsburgh Pirates,PNC Park,1257458.0,100,102,PIT,PIT,PIT
3011,2022,NL,SDN,SDP,W,2,162,81.0,89,73,...,116,0.987,San Diego Padres,Petco Park,2987470.0,92,92,SDP,SDN,SDN
3012,2022,NL,SFN,SFG,W,3,162,81.0,81,81,...,130,0.983,San Francisco Giants,Oracle Park,2482686.0,99,99,SFG,SFN,SFN
3013,2022,NL,SLN,STL,C,1,162,81.0,93,69,...,181,0.989,St. Louis Cardinals,Busch Stadium III,3320551.0,94,94,STL,SLN,SLN
3014,2022,NL,WAS,WSN,E,5,162,81.0,55,107,...,126,0.982,Washington Nationals,Nationals Park,2026401.0,94,96,WSN,MON,WAS

#### Q2. Show all the columns names of the Teams table using python - use sql to first output the Teams table as a dataframe like Q1 (2 point)

In [20]:
import pandas as pd
query = """
SELECT *
FROM Teams
"""
df = pd.read_sql(query, conn)
df.columns.tolist()

['yearID',
 'lgID',
 'teamID',
 'franchID',
 'divID',
 'Rank',
 'G',
 'Ghome',
 'W',
 'L',
 'DivWin',
 'WCWin',
 'LgWin',
 'WSWin',
 'R',
 'AB',
 'H',
 '2B',
 '3B',
 'HR',
 'BB',
 'SO',
 'SB',
 'CS',
 'HBP',
 'SF',
 'RA',
 'ER',
 'ERA',
 'CG',
 'SHO',
 'SV',
 'IPouts',
 'HA',
 'HRA',
 'BBA',
 'SOA',
 'E',
 'DP',
 'FP',
 'name',
 'park',
 'attendance',
 'BPF',
 'PPF',
 'teamIDBR',
 'teamIDlahman45',
 'teamIDretro']

#### Q3. Find the average number of wins per team-season (2 points)

In [21]:
import pandas as pd
query = """
SELECT AVG(W) AS avg_wins
FROM Teams
"""
df = pd.read_sql(query, conn)
df

    avg_wins
0  74.674627

# Aggregate Batting stats per team (10 points)
#### Q4. Using the Batting table, compute team totals for each season. The column names should be total_AB, total_H, total_HR, total_RBI

In [22]:
import pandas as pd
query = """
SELECT
    yearID,
    teamID,
    SUM(AB) AS total_AB,
    SUM(H) AS total_H,
    SUM(HR) AS total_HR,
    SUM(RBI) AS total_RBI
FROM Batting
GROUP BY yearID, teamID
"""
df = pd.read_sql(query, conn)
df

      yearID teamID  total_AB  total_H  total_HR  total_RBI
0       1871    BS1      1372      426         3      267.0
1       1871    CH1      1196      323        10      193.0
2       1871    CL1      1186      328         7      164.0
3       1871    FW1       746      178         2       94.0
4       1871    NY2      1404      403         1      213.0
...      ...    ...       ...      ...       ...        ...
3010    2022    SLN      5496     1386       197      739.0
3011    2022    TBA      5412     1294       139      634.0
3012    2022    TEX      5478     1308       198      670.0
3013    2022    TOR      5555     1464       200      756.0
3014    2022    WAS      5434     1351       136      579.0

[3015 rows x 6 columns]

# Join team wins (15 points)
#### Join the aggregated batting statistics with the Teams table to include: yearID, teamID, total_AB, total_H, total_HR, total_RBI, W. 
#### Assign the results of this query to a dataframe called df_team_stats
#### Hint - use CTE tables
#### 5 points for using CTE table
#### 5 points for proper join
#### 5 points for showing output

In [ ]:
import pandas as pd
query = """
WITH team_batting AS (
    SELECT
        yearID,
        teamID,
        SUM(AB) AS total_AB,
        SUM(H) AS total_H,
        SUM(HR) AS total_HR,
        SUM(RBI) AS total_RBI
    FROM Batting
    GROUP BY yearID, teamID
)

SELECT
    t.yearID,
    t.teamID,
    b.total_AB,
    b.total_H,
    b.total_HR,
    b.total_RBI,
    t.W
FROM Teams t
INNER JOIN team_batting b
    ON t.yearID = b.yearID
    AND t.teamID = b.teamID
WHERE t.yearID > 2000
"""
df_team_stats = pd.read_sql(query, conn)
df_team_stats

     yearID teamID  total_AB  total_H  total_HR  total_RBI   W
0      2001    ANA      5551     1447       158        662  75
1      2001    ARI      5595     1494       208        776  92
2      2001    ATL      5498     1432       174        696  88
3      2001    BAL      5472     1359       136        663  63
4      2001    BOS      5605     1493       198        739  82
..      ...    ...       ...      ...       ...        ...  ..
655    2022    SLN      5496     1386       197        739  93
656    2022    TBA      5412     1294       139        634  86
657    2022    TEX      5478     1308       198        670  68
658    2022    TOR      5555     1464       200        756  92
659    2022    WAS      5434     1351       136        579  55

[660 rows x 7 columns]

# Create team batting metrics (5 points)
#### Create the following variables using python
#### batting_avg = total_H / total_AB
#### hr_rate = total_HR / total_AB
#### rbi_rate = total_RBI / total_AB

In [25]:
df_team_stats["batting_avg"] = df_team_stats["total_H"] / df_team_stats["total_AB"]
df_team_stats["hr_rate"] = df_team_stats["total_HR"] / df_team_stats["total_AB"]
df_team_stats["rbi_rate"] = df_team_stats["total_RBI"] / df_team_stats["total_AB"]
df_team_stats

,yearID,teamID,total_AB,total_H,total_HR,total_RBI,W,batting_avg,hr_rate,rbi_rate
0,2001,ANA,5551,1447,158,662,75,0.260674,0.028463,0.119258
1,2001,ARI,5595,1494,208,776,92,0.267024,0.037176,0.138695
2,2001,ATL,5498,1432,174,696,88,0.260458,0.031648,0.126591
3,2001,BAL,5472,1359,136,663,63,0.248355,0.024854,0.121162
4,2001,BOS,5605,1493,198,739,82,0.266369,0.035326,0.131847
...,...,...,...,...,...,...,...,...,...,...
655,2022,SLN,5496,1386,197,739,93,0.252183,0.035844,0.134461
656,2022,TBA,5412,1294,139,634,86,0.239098,0.025684,0.117147
657,2022,TEX,5478,1308,198,670,68,0.238773,0.036145,0.122307
658,2022,TOR,5555,1464,200,756,92,0.263546,0.036004,0.136094
659,2022,WAS,5434,1351,136,579,55,0.248620,0.025028,0.106551

# Correlation Analysis (5 points)
#### Calculate the correlation between team wins (W) and the batting features

In [26]:
df_team_stats[["W", "batting_avg", "hr_rate", "rbi_rate"]].corr()

                    W  batting_avg   hr_rate  rbi_rate
W            1.000000     0.393552  0.139466  0.354389
batting_avg  0.393552     1.000000  0.044908  0.591500
hr_rate      0.139466     0.044908  1.000000  0.695086
rbi_rate     0.354389     0.591500  0.695086  1.000000

# Wins vs Home Runs (5 points)
#### Create a scatterplot showing wins against home runs also showing the difference over the years

In [27]:
import plotly.express as px
fig = px.scatter(
    df_team_stats,
    x="total_HR",
    y="W",
    color="yearID",
    title="Team Home Runs vs Wins",
    hover_data=["teamID"]
)

fig.update_layout(template="plotly_white")

fig.show()

# Predict Team Wins from Batting Statistics Using Python (15 points)
#### Prepare data to model (5 points)

In [29]:
from sklearn.model_selection import train_test_split

features = [
    "total_AB",
    "total_H",
    "total_HR",
    "total_RBI",
    "batting_avg",
    "hr_rate",
    "rbi_rate"
]

X = df_team_stats[features]
y = df_team_stats["W"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

#### Fit RandomForest Model (5 points)

In [31]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(
    n_estimators=300,
    random_state=42
)
rf.fit(X_train, y_train)
preds = rf.predict(X_test)

#### Show model performance (R2) (5 points)

In [32]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test, preds)
print("R2:", r2)

R2: 0.6587315298791023